# Generated by Django 4.0.3 on 2023-01-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecord',
            name='sales_person_number',
        ),
    ]
